# Generated by Django 4.0.4 on 2022-04-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='text',
            field=models.TextField(default=1, verbose_name='Описание продукта'),
            preserve_default=False,
        ),
    ]
